<a href="https://colab.research.google.com/github/saranyaece30111998-analyst/numpy-fundamentals/blob/main/NUMPY_ASSIGNMENT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Python DA Assignment 1—Numpy and Pandas**

# Numpy Array Operations:

In [ ]:
# importing numpy
import numpy as np

In [ ]:
#1. Create a 1D NumPy Array:
temperatures_w1=np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])


# 2. Inspection and Properties:

In [ ]:
# shape of array
print(" shape of array")
print(temperatures_w1.shape)

# data type of array
print("data type of array")
print(temperatures_w1.dtype)

#find the number of element
print("number of elements")
print(temperatures_w1.size)

 shape of array
(7,)
data type of array
float64
number of elements
7


# 3. Array Operations:

In [ ]:
# convert celsius in fahrenheit
Fahrenheit = (temperatures_w1* 9/5) + 32
print("temperature in fahrenheit")
print(Fahrenheit)


# maximum temperature
print("maximum temperature")
print(temperatures_w1.max())


# minimum temperature
print("minimum temperature")
print(temperatures_w1.min())

# mean temperature
print("mean temperature")
print(temperatures_w1.mean())


temperature in fahrenheit
[72.5  77.54 69.44 74.12 78.98 76.64 71.42]
maximum temperature
26.1
minimum temperature
20.8
mean temperature
23.542857142857144


# 4. Array Slicing and Indexing:

In [ ]:
# Extract the temperatures for the first three days of the week.
print("temperatures of three days")
print(temperatures_w1[0:3])

#Extract the temperatures for the weekend (last two days).
print("temperatures of weekend")
print(temperatures_w1[5:7])


#● Extract the temperatures for the middle three days of the week.
print("temperatures of middle three days")
print( temperatures_w1[2:5])


temperatures of three days
[22.5 25.3 20.8]
temperatures of weekend
[24.8 21.9]
temperatures of middle three days
[20.8 23.4 26.1]


# 2D ARRAY CREATION

In [ ]:
# Create 2D NumPy array for two weeks
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

#6. Inspect and Slice the 2D Array:

In [ ]:
# shape of 2d array
print("shape of 2d array")
print(temperatures.shape)

# data types of 2d array
print("data types of 2d array")
print(temperatures.dtype)

# number of elements

print("number of element in 2d array")
print(temperatures.size)

#slicing
# weekent temperatures of each weeks
print("weekend temperature of week 1" )
print(temperatures[0,5:7])
print("weekend temperature of week 2" )
print(temperatures[1,5:7])




shape of 2d array
(2, 7)
data types of 2d array
float64
number of element in 2d array
14
weekend temperature of week 1
[24.8 21.9]
weekend temperature of week 2
[22.8 20.1]


# **PANDAS SERIES**

In [ ]:
# crating pandas seies
import pandas as pd

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['rank1', 'rank2', 'rank3', 'rank4', 'rank5']
)
print(marks)

rank1    95
rank2    92
rank3    89
rank4    85
rank5    80
dtype: int64


#2. Indexing and Slicing:

In [ ]:
#Use the integer index position to access the mark of the 1st rank student.
print("mark of 1st rank student")
print(marks.iloc[0])

# mark of first three ranks
print("mark of first three ranks")
print(marks.loc[['rank1', 'rank2', 'rank3']])

#iloc accessor to retrieve the mark of the 3rd-ranked student.
print("mark of 3rd rank student")
print(marks.iloc[2])

# boolean mask to filter marks > 90
print("student with mark above 90")
print(marks[marks > 90])

mark of 1st rank student
100
mark of first three ranks
rank1    100
rank2     92
rank3     89
dtype: int64
mark of 3rd rank student
89
student with mark above 90
rank1    100
rank2     92
dtype: int64


# 3. Manipulating Series:

In [ ]:
# 1. modify the mark of the student with 1st rank to 100
marks['rank1'] = 100
print("mark of first rank")
print(marks['rank1'] )

mark of first rank
100


In [ ]:
# 2. remove the entry corresponding to the last rank
marks = marks.drop('rank5')

In [ ]:
# ● Compute the CGPA by dividing each mark in the Series by 10.
cgpa=marks/10
print("cgpa of students is ")
print(cgpa)

cgpa of students is 
rank1    10.0
rank2     9.2
rank3     8.9
rank4     8.5
dtype: float64


# **Pandas DataFrame:**

# 1. Creating Pandas DataFrame:

In [ ]:
import pandas as pd

# create the dataframe
transactions = pd.DataFrame({
    'transactionid': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'productcategory': ['electronics', 'clothing', 'electronics', 'furniture', 'clothing',
                        'electronics', 'furniture', 'clothing', 'furniture', 'electronics'],
    'region': ['north', 'south', 'north', 'east', 'west', 'north', 'east', 'west', 'south', 'north'],
    'amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

# display the dataframe
print(transactions)




   transactionid productcategory region  amount
0            101     electronics  north     200
1            102        clothing  south     150
2            103     electronics  north     300
3            104       furniture   east     450
4            105        clothing   west     200
5            106     electronics  north     250
6            107       furniture   east     300
7            108        clothing   west     180
8            109       furniture  south     350
9            110     electronics  north     400


# 2. Data Exploration:

In [ ]:
#displaying first five rows
print("first five rows is")
print(transactions.head())

# displaying last five rows
print("last five rows is")
print(transactions.tail())

# shape of data frames
print("shape of data frames")
print(transactions.shape)

# displaying columns
print("columns of data frame ")
print(transactions.columns)

#printing data tpes
print("data type of data frame")
print(transactions.dtypes)

first five rows is
   transactionid productcategory region  amount
0            101     electronics  north     200
1            102        clothing  south     150
2            103     electronics  north     300
3            104       furniture   east     450
4            105        clothing   west     200
last five rows is
   transactionid productcategory region  amount
5            106     electronics  north     250
6            107       furniture   east     300
7            108        clothing   west     180
8            109       furniture  south     350
9            110     electronics  north     400
shape of data frames
(10, 4)
columns of data frame 
Index(['transactionid', 'productcategory', 'region', 'amount'], dtype='object')
data type of data frame
transactionid       int64
productcategory    object
region             object
amount              int64
dtype: object


In [ ]:
# display only productcategory and amount
print(transactions[['productcategory', 'amount']])

# retrieve last 3 columns using iloc
print(transactions.iloc[:, -3:])

# filter rows where region is 'north' and amount > 200
print(transactions[(transactions['region'] == 'north') & (transactions['amount'] > 200)])

# value counts for productcategory
print(transactions['productcategory'].value_counts())

# unique values in region
print(transactions['region'].unique())

# group by region and find mean amount
print(transactions.groupby('region')['amount'].mean())

  productcategory  amount
0     electronics     200
1        clothing     150
2     electronics     300
3       furniture     450
4        clothing     200
5     electronics     250
6       furniture     300
7        clothing     180
8       furniture     350
9     electronics     400
  productcategory region  amount
0     electronics  north     200
1        clothing  south     150
2     electronics  north     300
3       furniture   east     450
4        clothing   west     200
5     electronics  north     250
6       furniture   east     300
7        clothing   west     180
8       furniture  south     350
9     electronics  north     400
   transactionid productcategory region  amount
2            103     electronics  north     300
5            106     electronics  north     250
9            110     electronics  north     400
productcategory
electronics    4
clothing       3
furniture      3
Name: count, dtype: int64
['north' 'south' 'east' 'west']
region
east     375.0
north    287

# 3. Manipulating the DataFrame:

In [ ]:
# modify amount for transactionid 102 to 165
transactions.loc[transactions['transactionid'] == 102, 'amount'] = 165

# add new column discount (10% of amount)
transactions['discount'] = transactions['amount'] * 0.10

# remove row with transactionid 109
transactions = transactions[transactions['transactionid'] != 109]

# delete the discount column
transactions = transactions.drop(columns=['discount'])

In [ ]:
print(transactions)

   transactionid productcategory region  amount
0            101     electronics  north     200
1            102        clothing  south     150
2            103     electronics  north     300
3            104       furniture   east     450
4            105        clothing   west     200
5            106     electronics  north     250
6            107       furniture   east     300
7            108        clothing   west     180
8            109       furniture  south     350
9            110     electronics  north     400
