<a href="https://colab.research.google.com/github/saranyaece30111998-analyst/numpy-fundamentals/blob/main/python_da.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install NumPy

In [ ]:
import numpy as np


In [ ]:
# 1d array
arr=np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
#2d array
arr=np.array([[1,2,3], [4,5,6]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.size

6

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.ndim

2