<a href="https://colab.research.google.com/github/saranyaece30111998-analyst/numpy-fundamentals/blob/main/python_da.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install NumPy

In [ ]:
import numpy as np


In [ ]:
# 1d array
arr=np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
#2d array
arr=np.array([[1,2,3], [4,5,6]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.size

6

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.ndim

2

# BASIC STATISTICAL AND MATHEMATICAL OPERATIONS

In [2]:
import numpy as np
# Create a 2D NumPy array with 2 rows and 3 columns
arr =np.array([[6,2,3],
              [4,5,1]])

In [3]:
# Minimum value in the array and index
arr.min()
print(np.argmin(arr))

5


In [4]:
# Maximum value in the array
print(arr.max())
print(np.argmax(arr))

6
0


In [5]:
# Sum of all elements
print(arr.sum())

21


In [6]:
# Product of all elements
print(np.prod(arr))

720


In [7]:
# Mean / Average of the array
print(arr.mean())
print(arr.var())
print(arr.std())

3.5
2.9166666666666665
1.707825127659933


NUMPY RANDOM FUNCTIONS

In [8]:
# 1. np.random.rand(d1, d2,..)
# Uniform random numbers in(0,1)

np.random.rand(5,2)

array([[0.87341902, 0.00769281],
       [0.26485968, 0.97980639],
       [0.94422109, 0.35737166],
       [0.57744168, 0.66350272],
       [0.40155702, 0.43735689]])

In [9]:
# 2. np.random.randn(d1, d2, ...)
# Standard normal distribution (mean=0, std=1)

np.random.randn(5,2)

array([[ 0.56925851,  0.96060745],
       [ 1.12954538,  0.44127456],
       [ 0.8796494 ,  1.1260551 ],
       [-1.88380912,  0.70883957],
       [ 0.15754143, -0.02470292]])

In [10]:
# 3. np.random.randint(low, high, size)
#Random integers in a range
np.random.randint(2,4,30)

array([2, 3, 3, 2, 3, 2, 3, 2, 3, 2, 3, 3, 3, 2, 2, 3, 3, 2, 3, 3, 2, 2,
       3, 2, 2, 3, 2, 2, 3, 2])

In [11]:
# 4. np.random.choice(arr, size)
#Random sample from an existing array
np.random.seed(42)
arr =np.array([2,3,4,5,6])
np.random.choice(arr,20)


array([5, 6, 4, 6, 6, 3, 4, 4, 4, 6, 5, 4, 6, 3, 5, 3, 5, 6, 2, 5])

In [12]:
# 5. np.random.seed(n)
#Set seed for reproducibility
np.random.seed(42)